In [48]:
import random
import pandas as pd
import numpy as np
from faker import Faker
from vn_fullname_generator import generator

In [21]:
danhsach_nganhang = pd.read_csv('banking_resource_production.csv')
danhsach_nganhang.head(5)

,#,ShortName,AndroidAppId,LogoApp,Name,Code,Bin,Top
0,1.0,VPBank,com.vnpay.vpbankonline,uploads/vpbank.png,Ngân hàng TMCP Việt Nam Thịnh Vượng,VPB,970432.0,4.0
1,2.0,BIDV,com.vnpay.bidv,uploads/bidv.png,Ngân Hàng TMCP Đầu tư và Phát triển Việt Nam,BIDV,970418.0,2.0
2,3.0,Vietcombank,com.VCB,uploads/vcb.png,Ngân hàng TMCP Ngoại Thương Việt Nam,VCB,970436.0,1.0
3,4.0,VietinBank,com.vietinbank.ipay,uploads/vietinbank.png,Ngân hàng TMCP Công Thương Việt Nam,ICB,970415.0,3.0
4,5.0,MB Bank,com.mbmobile,uploads/mbbank.png,Ngân hàng TMCP Quân Đội,MB,970422.0,6.0

In [49]:

fake = Faker('vi_VN')

banks = danhsach_nganhang['ShortName'].to_numpy()
bins = danhsach_nganhang['Bin'].to_numpy()
account_status = ['Active', 'Inactive', 'Closed', 'Frozen']
gender = [0, 1]
def generate_fake_bank_data(num_records=1000000):
    data = []
    for _ in range(num_records):

        bank = random.choice(banks)
        bank_index = np.where(banks == bank)
        bin = bins[bank_index][0]

        account_number = fake.random_number(digits=11, fix_len=True)
        account_holder = generator.generate(random.choice(gender))
        bank = bank
        balance = random.randint(0, 100000000)
        open_date = fake.date_between(start_date='-5y', end_date='today')
        status = random.choices(account_status, weights=[0.6, 0.2, 0.1, 0.1], k=1)[0]
        cccd = str(fake.random_int(min=100000000000, max=999999999999, step=1))  # Số CCCD 12 chữ số
        cccd = cccd.zfill(13)
        data.append([account_number, account_holder, cccd, bank, bin, balance, open_date, status])

    columns = ['AccountNo', 'OwnerName', 'IdCardNo', 'BankName', 'Bin', 'Balance', 'OpenedAt', 'Status']
    return pd.DataFrame(data, columns=columns)

df = generate_fake_bank_data()
df.drop_duplicates(subset='AccountNo', inplace=True)
df.to_csv('fake_bank_accounts.csv', index=False, encoding='utf-8')

print("Dataset đã được tạo và lưu vào file 'fake_bank_accounts.csv'")

Dataset đã được tạo và lưu vào file 'fake_bank_accounts.csv'

In [50]:
bank_accounts = pd.read_csv('fake_bank_accounts.csv')
bank_accounts.head()

,AccountNo,OwnerName,IdCardNo,BankName,Bin,Balance,OpenedAt,Status
0,90038091173,Trương Minh Vương,768302105067,Indovina Bank,970434.0,77411770,2024-02-19,Active
1,32307158515,Lê Thái Lan,383222432656,Techcombank,970407.0,78005125,2022-04-20,Inactive
2,44108618887,Huỳnh Tú Tâm,407611501636,Timo,963388.0,25767619,2024-05-21,Frozen
3,69344597494,Võ Quỳnh Trang,848532633361,Agribank,970405.0,18027322,2019-12-06,Closed
4,37111152318,Đoàn Mỹ Nhân,597990755643,BIDV,970418.0,92538361,2022-08-31,Closed

In [51]:
#768302105067
#068203005832
df.drop_duplicates(subset='AccountNo', inplace=True)

In [52]:
df.to_csv('fake_bank_accounts.csv', index=False, encoding='utf-8')